### ISSUE TITLE
Why does the github say:  pTokens dapp available here (https://dapp.ptokens.io/)

### ISSUE THREAD

**Issue by tr4vis** [pnetwork-association/ptokens-dapp#95]
Is (https://dapp.ptokens.io/) where the app actually is? It's a dead link. Not really great security if github is the official source of info...

**Comment by envin3** [comment]
[dapp.p.network](https://dapp.p.network/) is the correct url until end of December.

**Comment by tr4vis** [comment]
Hi, thanks for your help. Approximately what amount of EOS resources (CPU, Network, etc.) are needed to do a pegout? Thanks again! 


 
 
  On Thu, Nov 14, 2024 at 5:02 PM, ***@***.***> wrote:   


dapp.p.network is the correct url until end of December.

**Comment by tr4vis** [comment]
Hi,
Congratulations on the great progress on pNetwork v4 and the EOS Foundation grant! I've been a user for some time and very excited for things to come.
I did a pegout transaction while v2 was still active but am still waiting to see it completed. Can you please assist with seeing it through? 
Pbtc on eosio
Tx: 
2b99cb73562a24d22981d7ca57dd40e6606a167de840be51d8a790bb8a3587c3
My prior one took a couple of days so hoping to see this one finalized asap as well.
Thank you, again!
